// let hello = 'hello';
// let owu = 'owu';
// let com = 'com';
// let ua = 'ua';
// let q = 1;
// let w = 10;
// let e = -999;
// let r = 123;
// let a = 3.14;
// let s = 2.7;
// let d = 16;
// let t = true;
// let f = false;
//
// console.log(hello);
// console.log(owu);
// console.log(com);
// console.log(ua);
// console.log(q);
// console.log(w);
// console.log(e);
// console.log(r);
// console.log(a);
// console.log(s);
// console.log(d);
// console.log(t);
// console.log(f);
//
// alert(hello);
// alert(owu);
// alert(com);
// alert(ua);
// alert(q);
// alert(w);
// alert(e);
// alert(r);
// alert(a);
// alert(s);
// alert(d);
// alert(t);
// alert(f);
//
// document.write(`<p>${hello} ${owu} ${com} ${ua} ${q} ${w} ${e} ${r} ${a} ${s} ${d} ${t} ${f}</p>`);
// document.write(owu);
// document.write(com);
// document.write(ua);
// document.write(q);
// document.write(w);
// document.write(e);
// document.write(r);
// document.write(a);
// document.write(s);
// document.write(d);
// document.write(t);
// document.write(f);
//
// hello = 'VLAD ';
// owu = 'YAKUBETS ';
// com = 'HOME';
// ua = 'work';
// q = 10;
// w = 15;
// e = -99;
// r = 13;
// a = 3;
// s = 2.99;
// d = 17;
// t = false;
// f = true;
//
// console.log(hello);
// console.log(owu);
// console.log(com);
// console.log(ua);
// console.log(q);
// console.log(w);
// console.log(e);
// console.log(r);
// console.log(a);
// console.log(s);
// console.log(d);
// console.log(t);
// console.log(f);
//
// alert(hello);
// alert(owu);
// alert(com);
// alert(ua);
// alert(q);
// alert(w);
// alert(e);
// alert(r);
// alert(a);
// alert(s);
// alert(d);
// alert(t);
// alert(f);
//
// document.write(`<p>${hello} ${owu} ${com} ${ua} ${q} ${w} ${e} ${r} ${a} ${s} ${d} ${t} ${f}</p>`);
// document.write(owu);
// document.write(com);
// document.write(ua);
// document.write(q);
// document.write(w);
// document.write(e);
// document.write(r);
// document.write(a);
// document.write(s);
// document.write(d);
// document.write(t);
// document.write(f);

let day = 23;
let month = 3;
let year = 2021;
let name ='VLAD';
let surName ='Yakubets';
let guruYear ='Dragon';

console.log(day,month,year,name,surName,guruYear);
alert(day);
alert(month);
alert(year);
alert(name);
alert(surName);
alert(guruYear);
document.write(`<p>${day}.${month}.${year}--${name} ${surName} ${guruYear}</p>`);